/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElCard: typeof import('element-plus/es')['ElCard']
    ElText: typeof import('element-plus/es')['ElText']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    HelloWorld: typeof import('./../src/components/HelloWorld.vue')['default']
    NavBar: typeof import('./../src/components/NavBar/index.vue')['default']
    Unpacker: typeof import('./../src/components/Unpacker/index.vue')['default']
  }
}
